# Generated by Django 6.0.5 on 2026-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_mock_test_unlocked',
            field=models.BooleanField(default=False, help_text='Mock test tizimi uchun bir martalik xarid'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Video/audio darslar oylik obunasi'),
        ),
    ]
