# Generated by Django 6.0.5 on 2026-07-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='award', help_text='Lucide icon name', max_length=50)),
                ('rarity', models.CharField(choices=[('common', 'Oddiy'), ('rare', 'Noyob'), ('epic', 'Epos'), ('legendary', 'Afsonaviy')], default='common', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('coin_reward', models.IntegerField(default=10)),
                ('target_count', models.IntegerField(default=1)),
                ('action_type', models.CharField(choices=[('test', 'Test topshirish'), ('battle', '1v1 Arena jangi'), ('lesson', "Dars o'qish")], default='test', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('mission', 'Vazifa'), ('battle', 'Jang'), ('achievement', 'Yutuq'), ('system', 'Tizim')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='ProfileMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailymission')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='accounts.profile')),
            ],
            options={
                'unique_together': {('profile', 'mission', 'date')},
            },
        ),
    ]
