# Generated by Django 6.0.5 on 2026-07-14 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemission',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
