# Generated by Django 6.0.5 on 2026-07-07 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='bot_avatar_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='battle',
            name='bot_elo_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='bot_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='battle',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_vs_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleround',
            name='bot_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.choice'),
        ),
        migrations.AddField(
            model_name='battleround',
            name='bot_is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
