# Generated by Django 6.0.5 on 2026-07-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_mapchallenge_options'),
        ('tests_app', '0011_testset_created_by_testset_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('flashcards', 'Flesh-kartalar'), ('match_pairs', 'Juftlikni top'), ('quiz_race', 'Tezkor viktorina')], default='flashcards', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='tests_app.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(help_text='Old tomon / atama / savol', max_length=500)),
                ('back_text', models.CharField(help_text="Orqa tomon / ta'rif / javob", max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/%Y/%m/')),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='games.game')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
