# Generated by Django 6.0.5 on 2026-07-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_gameitem'),
        ('tests_app', '0016_seed_subjects_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcharacter',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='tests_app.subject'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='tests_app.subject'),
        ),
        migrations.AddField(
            model_name='mapchallenge',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_challenges', to='tests_app.subject'),
        ),
    ]
