# Generated by Django 6.0.5 on 2026-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_test_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedback',
            name='detailed_mistakes',
            field=models.JSONField(default=list, help_text="Per-question breakdown from the AI: topic, question, student's wrong/skipped answer, the correct answer, why it matters, and a memory aid. Empty when the rule-based fallback (no Groq) generated this feedback instead."),
        ),
    ]
