# Generated by Django 6.0.5 on 2026-07-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0005_aifeedback_detailed_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='ai_grading_note',
            field=models.CharField(blank=True, help_text="Ochiq savol uchun AI bahosining qisqa izohi (nega to'g'ri/xato deb topilgani).", max_length=300),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text="Ochiq savollar uchun o'quvchi kiritgan matnli javob."),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', "Variantli (bitta to'g'ri javob)"), ('open', 'Ochiq javobli (AI baholaydi)')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='reference_answer',
            field=models.TextField(blank=True, help_text="Ochiq savollar uchun namunaviy to'g'ri javob — Groq shu bilan solishtirib, o'quvchining matnli javobini to'g'ri/xato deb baholaydi. Variantli savollarda ishlatilmaydi."),
        ),
    ]
