# Generated by Django 6.0.5 on 2026-07-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0006_attemptanswer_ai_grading_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A, B, C, D...', max_length=5)),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='matching_data',
            field=models.JSONField(blank=True, default=dict, help_text="Juftlashtirish savoli uchun tanlangan juftliklar, masalan {'I': 'd', 'II': 'a'}."),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', "Variantli (bitta to'g'ri javob)"), ('open', 'Ochiq javobli (AI baholaydi)'), ('matching', "Juftlashtirish (I/II/III... ni a/b/c... bilan bog'lash)"), ('grouped', 'Umumiy javob banki (bir nechta savol bitta A-F bankidan javob tanlaydi)')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='grouped_option',
            field=models.ForeignKey(blank=True, help_text='Umumiy javob banki (grouped) savoli uchun tanlangan variant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.groupoption'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_group_option',
            field=models.ForeignKey(blank=True, help_text="Faqat 'grouped' turidagi savollar uchun — bankdagi to'g'ri variant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.groupoption'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(help_text="Masalan: '33-35 savollarga mos javoblarni quyidagi A-F variantlaridan tanlang'")),
                ('order', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='tests_app.test')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='groupoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests_app.questiongroup'),
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Faqat 'grouped' turidagi savollar uchun — shu savol qaysi umumiy javob bankiga tegishli.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_app.questiongroup'),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_key', models.CharField(blank=True, help_text="Chap ustun belgisi (I, II, III...). Bo'sh qoldirilsa, bu qator faqat chalg'ituvchi (distractor) variant sifatida o'ng ustunda ko'rinadi.", max_length=10)),
                ('left_text', models.CharField(blank=True, max_length=300)),
                ('right_key', models.CharField(help_text="O'ng ustun belgisi (a, b, c...)", max_length=10)),
                ('right_text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='tests_app.question')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'right_key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupoption',
            unique_together={('group', 'label')},
        ),
    ]
