"""Universal test system rename/expansion.

Hand-written (not autogenerated) so every rename uses RenameModel/RenameField explicitly —
this preserves every existing row, PK and FK relationship (including the real users' 24
existing Attempt records) instead of risking a drop-and-recreate that Django's interactive
rename-detection could produce when run non-interactively.
"""
import django.db.models.deletion
from django.db import migrations, models


def rename_question_type_values(apps, schema_editor):
    Question = apps.get_model('tests_app', 'Question')
    Question.objects.filter(question_type='mcq').update(question_type='single_choice')
    Question.objects.filter(question_type='open').update(question_type='open_written')
    Question.objects.filter(question_type='grouped').update(question_type='grouped_item')


def reverse_question_type_values(apps, schema_editor):
    Question = apps.get_model('tests_app', 'Question')
    Question.objects.filter(question_type='single_choice').update(question_type='mcq')
    Question.objects.filter(question_type='open_written').update(question_type='open')
    Question.objects.filter(question_type='grouped_item').update(question_type='grouped')


def create_default_subject(apps, schema_editor):
    Subject = apps.get_model('tests_app', 'Subject')
    TestSet = apps.get_model('tests_app', 'TestSet')
    subject, _ = Subject.objects.get_or_create(slug='tarix', defaults={'name': 'Tarix'})
    TestSet.objects.filter(subject__isnull=True).update(subject=subject)


def reverse_default_subject(apps, schema_editor):
    # Leaving TestSet.subject populated on reverse is harmless (the field itself is
    # removed by the AddField reversal right after), so this is a deliberate no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0008_test_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={'ordering': ['name']},
        ),

        # --- Renames: table/column renamed in place, every existing row/PK/FK survives ---
        migrations.RenameModel(old_name='Test', new_name='TestSet'),
        migrations.RenameModel(old_name='Choice', new_name='AnswerOption'),
        migrations.RenameField(model_name='question', old_name='text', new_name='body'),
        migrations.RenameField(model_name='questiongroup', old_name='test', new_name='test_set'),

        migrations.AlterField(
            model_name='question',
            name='body',
            # Historically a django-ckeditor RichTextField; kept as a plain TextField here
            # (same underlying TEXT column) so this migration no longer depends on the
            # removed CKEditor 4 package. Migration 0014 re-alters it to CKEditor5Field.
            field=models.TextField(
                help_text="Savol matni — qalin/kursiv, ro'yxatlar va jadvallarni CKEditor orqali "
                          "to'g'ridan-to'g'ri qo'shish mumkin (masalan 'Asr / Voqea' jadvalli savollar uchun).",
            ),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='test_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='tests_app.testset'),
        ),

        # --- New TestSet/Question/AttemptAnswer fields ---
        migrations.AddField(
            model_name='testset',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sets', to='tests_app.subject'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='questions',
            field=models.ManyToManyField(related_name='test_sets', to='tests_app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Xarita, Venn diagramma yoki sxema rasmi.', null=True, upload_to='tests/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_position',
            field=models.CharField(choices=[('after_body', 'Savol matnidan keyin'), ('before_body', 'Savol matnidan oldin')], default='after_body', max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, help_text="Bu savol uchun ball og'irligi."),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text="Javob izohi — foydalanuvchiga natija sahifasida ko'rsatiladi (ixtiyoriy)."),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('single_choice', "Oddiy test (bitta to'g'ri javob)"),
                    ('image_based', 'Rasmli savol (xarita/diagramma + variantlar)'),
                    ('table_based', 'Jadvalli savol (variantlar bilan)'),
                    ('matching', "Moslashtirish (I/II/III... ni a/b/c... bilan bog'lash)"),
                    ('grouped_item', "Guruhlangan savol (umumiy A-F javob bankidan)"),
                    ('open_written', 'Yozma (ochiq) savol — AI baholaydi'),
                ],
                default='single_choice', max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='open_answers',
            field=models.JSONField(blank=True, default=dict, help_text="Qism-savollarga (SubQuestion) bo'lingan ochiq savol uchun har bir band bo'yicha javob, masalan {'a': 'Varfolomey kechasi', 'b': 'Katerina Medichi'}."),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='open_grading',
            field=models.JSONField(blank=True, default=dict, help_text="Qism-savolli ochiq javob uchun har bir band bo'yicha AI bahosi, masalan {'a': {'is_correct': true, 'note': '...'}, 'b': {...}}."),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text="Bo'linmagan ochiq savol uchun o'quvchi kiritgan matnli javob."),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='grouped_option',
            field=models.ForeignKey(blank=True, help_text="Guruhlangan (grouped_item) savol uchun tanlangan variant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.groupoption'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Faqat 'grouped_item' turidagi savollar uchun — shu savol qaysi umumiy javob bankiga tegishli.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests_app.questiongroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_group_option',
            field=models.ForeignKey(blank=True, help_text="Faqat 'grouped_item' turidagi savollar uchun — bankdagi to'g'ri variant.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests_app.groupoption'),
        ),

        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='a, b, c...', max_length=5)),
                ('text', models.TextField()),
                ('reference_answer', models.TextField(help_text="Groq shu namunaviy javob bilan solishtirib, o'quvchining matnli javobini baholaydi.")),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='tests_app.question')),
            ],
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='subquestion',
            unique_together={('question', 'label')},
        ),

        # --- Data migrations: run after every column exists ---
        migrations.RunPython(rename_question_type_values, reverse_question_type_values),
        migrations.RunPython(create_default_subject, reverse_default_subject),
    ]
