# Generated by Django 6.0.5 on 2026-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0009_universal_test_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reference_answer',
            field=models.TextField(blank=True, help_text="Ochiq savollar uchun namunaviy to'g'ri javob — Groq shu bilan solishtirib, o'quvchining matnli javobini to'g'ri/xato deb baholaydi. Faqat shu savol qism-savollarga (SubQuestion) bo'linmagan bo'lsa ishlatiladi."),
        ),
    ]
