# Generated by Django 6.0.5 on 2026-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0012_backfill_testset_publish_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='question_order',
            field=models.JSONField(blank=True, default=list, help_text="Savollar tartibi (Question id'lari ro'yxati) — test ustaxonasidagi drag-drop tartibi shu yerda saqlanadi. Bo'sh bo'lsa, id bo'yicha tartiblanadi."),
        ),
    ]
