# Generated by Django 6.0.5 on 2026-07-14 12:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0013_testset_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text="Savol matni — qalin/kursiv, ro'yxatlar va jadvallarni CKEditor orqali to'g'ridan-to'g'ri qo'shish mumkin (masalan 'Asr / Voqea' jadvalli savollar uchun)."),
        ),
    ]
