# Generated by Django 6.0.5 on 2026-07-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profile_xp_desc_idx'),
        ('tests_app', '0016_seed_subjects_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_wrong', models.PositiveIntegerField(default=1)),
                ('times_reviewed', models.PositiveIntegerField(default=0)),
                ('mastered', models.BooleanField(db_index=True, default=False)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mastered', '-times_wrong', 'updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subjectscore',
            index=models.Index(fields=['subject', '-xp'], name='subjscore_subj_xp_idx'),
        ),
        migrations.AddField(
            model_name='revisionitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='revisionitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to='tests_app.question'),
        ),
        migrations.AddField(
            model_name='revisionitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_items', to='tests_app.subject'),
        ),
        migrations.AddIndex(
            model_name='revisionitem',
            index=models.Index(fields=['profile', 'mastered'], name='tests_app_r_profile_55046f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='revisionitem',
            unique_together={('profile', 'question')},
        ),
    ]
