# Generated by Django 5.0 on 2026-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_referral_code_profile_referred_by_and_more'),
        ('tests_app', '0017_revisionitem_subjectscore_subjscore_subj_xp_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['is_completed', 'completed_at'], name='tests_app_a_is_comp_524e33_idx'),
        ),
    ]
