# Generated by Django 6.0.5 on 2026-08-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0018_alter_attempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='answered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='time_spent_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
