# Generated by Django 6.1 on 2026-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0019_attemptanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('history', 'Tarix'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
        migrations.AlterField(
            model_name='testset',
            name='category',
            field=models.CharField(choices=[('history', 'Tarix'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
    ]
