# Generated by Django 6.1 on 2026-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0020_alter_question_category_alter_testset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('history', 'Mavzulashtirilgan'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
        migrations.AlterField(
            model_name='testset',
            name='category',
            field=models.CharField(choices=[('history', 'Mavzulashtirilgan'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
    ]
