# Generated by Django 6.1 on 2026-09-05 12:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0021_alter_question_category_alter_testset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='annotations',
            field=models.JSONField(blank=True, default=dict, help_text="O'quvchining matn ustidagi belgilari: sariq bo'yoq (highlight) va qaydlar. Bo'lim id'si bo'yicha kalitlanadi, masalan {'12': [{'start': 40, 'end': 58, 'color': 'yellow', 'note': ''}]}. Faqat shu urinishga tegishli — baholashga ta'sir qilmaydi."),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='ai_level',
            field=models.CharField(blank=True, help_text="Writing javobiga qo'yilgan taxminiy CEFR darajasi (A1...C2).", max_length=5),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='ai_score',
            field=models.FloatField(blank=True, help_text="Writing topshirig'i uchun AI qo'ygan umumiy ball (0-5). Tekshiruv premium bo'lgani uchun bo'sh qolishi mumkin — o'quvchi yozgan, lekin baholatmagan.", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Imtihon varaqasidagi rasmiy raqam (1-35). Matn ichidagi {{N}} bo'shliqlari shu raqam orqali savolga ulanadi.", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_words',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Bo'shliqqa yozish mumkin bo'lgan so'z chegarasi (masalan 'ONE WORD ONLY' — 1).", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_words',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Faqat 'writing_task' uchun — talab qilinadigan eng kam so'z soni.", null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tfng_style',
            field=models.CharField(choices=[('tf', 'TRUE / FALSE / NOT GIVEN'), ('yn', 'YES / NO / NOT GIVEN')], default='tf', help_text="Faqat 'tfng' turi uchun — TRUE/FALSE yoki YES/NO uslubi.", max_length=2),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='open_grading',
            field=models.JSONField(blank=True, default=dict, help_text="Qism-savolli ochiq javob uchun har bir band bo'yicha AI bahosi, masalan {'a': {'is_correct': true, 'note': '...'}, 'b': {...}}. Writing topshirig'i uchun esa mezonlar kesimi: {'task': 4, 'coherence': 3, 'lexis': 4, 'grammar': 3, 'strengths': [...], 'improvements': [...]}."),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', "Oddiy test (bitta to'g'ri javob)"), ('image_based', 'Rasmli savol (xarita/diagramma + variantlar)'), ('table_based', 'Jadvalli savol (variantlar bilan)'), ('matching', "Moslashtirish (I/II/III... ni a/b/c... bilan bog'lash)"), ('grouped_item', 'Guruhlangan savol (umumiy A-F javob bankidan)'), ('open_written', 'Yozma (ochiq) savol — AI baholaydi'), ('gap_fill', "Bo'shliqni to'ldirish (matndan aniq so'z)"), ('tfng', 'TRUE / FALSE / NOT GIVEN'), ('writing_task', "Writing topshirig'i (esse/xat) — AI baholaydi")], default='single_choice', max_length=15),
        ),
        migrations.CreateModel(
            name='AcceptedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_answers', to='tests_app.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')], default='reading', max_length=10)),
                ('part_number', models.PositiveSmallIntegerField(default=1, help_text='Part 1, Part 2 ... (rasmiy raqami).')),
                ('title', models.CharField(blank=True, help_text="Matn sarlavhasi, masalan 'INJURED BIRD'.", max_length=200)),
                ('instruction', models.TextField(blank=True, help_text="Part ko'rsatmasi, masalan 'Read the texts. Fill in each gap with ONE word.'")),
                ('passage', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="O'qish matni yoki konspekt. Matn ichidagi bo'shliqlar {{9}} ko'rinishida belgilanadi — {{...}} ichidagi raqam savolning imtihon raqami (Question.exam_number).")),
                ('audio', models.FileField(blank=True, help_text='Listening parti uchun audio fayl.', null=True, upload_to='cefr/audio/%Y/%m/')),
                ('audio_url', models.URLField(blank=True, help_text="Tashqi audio havolasi (fayl o'rniga).", max_length=500)),
                ('audio_play_limit', models.PositiveSmallIntegerField(default=2, help_text='Audio necha marta eshittiriladi. 0 — cheksiz (mashq rejimi).')),
                ('image', models.ImageField(blank=True, help_text='Xarita/sxema rasmi — masalan Listening Part 4 (joylarni belgilash).', null=True, upload_to='cefr/sections/%Y/%m/')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text="Shu partga ajratilgan vaqt. Bo'sh bo'lsa — testning umumiy vaqti ishlatiladi.", null=True)),
                ('order', models.IntegerField(default=0)),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests_app.testset')),
            ],
            options={
                'ordering': ['order', 'part_number', 'id'],
                'unique_together': {('test_set', 'skill', 'part_number')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Savol qaysi partga (matn/audio blokiga) tegishli.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests_app.examsection'),
        ),
    ]
