# Generated by Django 6.1 on 2026-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0022_attempt_annotations_attemptanswer_ai_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='audio_plays',
            field=models.JSONField(blank=True, default=dict, help_text="Listening partlari necha marta eshitilgani: {'12': 2}. Klientda emas, shu yerda sanaladi — aks holda sahifani yangilash bilan cheklovni aylanib o'tish mumkin bo'lardi."),
        ),
    ]
