# Generated by Django 6.1 on 2026-09-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0023_attempt_audio_plays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tfng_style',
            field=models.CharField(blank=True, choices=[('tf', 'TRUE / FALSE / NOT GIVEN'), ('yn', 'YES / NO / NOT GIVEN')], default='tf', help_text="Faqat 'tfng' turi uchun — TRUE/FALSE yoki YES/NO uslubi.", max_length=2),
        ),
    ]
