# Generated by Django on 2026-09-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0024_alter_question_tfng_style'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='is_live_mock',
            field=models.BooleanField(default=False, help_text="Belgilangan vaqtda o'tkaziladigan katta jonli mock imtihon."),
        ),
        migrations.AddField(
            model_name='testset',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Mock imtihonning aniq boshlanish vaqti (masalan, ertaga 21:30).", null=True),
        ),
        migrations.AddField(
            model_name='testset',
            name='remind_users',
            field=models.ManyToManyField(blank=True, help_text="Imtihon boshlanganda Telegram orqali eslatish so'ragan foydalanuvchilar.", related_name='mock_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
