# Generated by Django on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0025_testset_is_live_mock_testset_remind_users_testset_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='notify_all',
            field=models.BooleanField(default=True, help_text="Mock boshlanganda barcha bot foydalanuvchilariga yuborish (aks holda faqat eslatma so'raganlarga)."),
        ),
        migrations.AddField(
            model_name='testset',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text="Jonli mock boshlanish xabari jo'natilgan vaqt (bir marta yuboriladi).", null=True),
        ),
    ]
