# Generated by Django 6.0.5 on 2026-09-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0027_examsurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAttemptResult',
            fields=[
            ],
            options={
                'verbose_name': 'Mock natijasi',
                'verbose_name_plural': 'Mock natijalari (Jonli Mock)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tests_app.attempt',),
        ),
    ]
