# Generated by Django 6.0.5 on 2026-09-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0030_attempt_hot_path_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attempt',
            new_name='tests_app_a_profile_03774e_idx',
            old_name='tests_app_a_prof_test_comp_idx',
        ),
        migrations.RenameIndex(
            model_name='attempt',
            new_name='tests_app_a_test_id_1b6b9f_idx',
            old_name='tests_app_a_test_comp_idx',
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_speed_flagged',
            field=models.BooleanField(default=False, help_text='Test shubhali tezlikda topshirilgan (masalan 45 savolni 3 daqiqada).'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0, help_text="O'quvchi test vaqtida brauzer tabini necha marta almashtirdi."),
        ),
    ]
