# Generated by Django 6.0.5 on 2026-07-17 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profile_xp_desc_idx'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakFreezeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_covered', models.PositiveIntegerField(default=1, help_text="Qoplangan (o'tkazib yuborilgan) kunlar soni.")),
                ('streak_before', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_logs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='shop_streak_profile_6f0c84_idx')],
            },
        ),
    ]
