# Generated by Django 6.0.5 on 2026-08-21 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_profile_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_percent', models.FloatField(help_text="Og'irlikli o'rtacha o'zlashtirish, 0–100")),
                ('predicted_dtm', models.PositiveIntegerField(help_text='Taxminiy DTM balli (chiziqli moslashtirish)')),
                ('confidence', models.FloatField(help_text="0–1: javoblar hajmi va mavzu qamroviga bog'liq")),
                ('sample_size', models.PositiveIntegerField(help_text='Hisobga olingan javoblar soni')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_predictions', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Ball bashorati',
                'verbose_name_plural': 'Ball bashoratlari',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['profile', 'calculated_at'], name='analytics_s_profile_e43bb7_idx')],
            },
        ),
    ]
