# Generated by Django 6.0.5 on 2026-07-15 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Yoqilganda oddiy foydalanuvchilar uchun sayt vaqtincha yopiladi; faqat super admin kira oladi.'),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('students', "O'quvchilar"), ('teachers', "O'qituvchilar"), ('premium', 'Premium foydalanuvchilar')], default='all', max_length=20)),
                ('via_telegram', models.BooleanField(default=False)),
                ('recipients_count', models.IntegerField(default=0)),
                ('telegram_sent_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
