# Generated by Django 6.0.5 on 2026-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_sitesettings_maintenance_mode_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, help_text="Ixtiyoriy — xabar bilan birga ko'rinadigan rasm", null=True, upload_to='broadcasts/'),
        ),
    ]
