# Generated by Django 6.0.5 on 2026-09-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_rename_site_to_ilmildizi'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('other', 'Boshqa')], default='groq', max_length=20)),
                ('model_name', models.CharField(default='llama-3.3-70b-versatile', max_length=100)),
                ('endpoint', models.CharField(blank=True, help_text='Qaysi funksiya chaqirdi (masalan: grade_open_answers)', max_length=200)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0, help_text='Taxminiy narx (USD)')),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='API javob vaqti (ms)')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI foydalanish logi',
                'verbose_name_plural': 'AI foydalanish loglari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='broadcast',
            name='is_sent',
            field=models.BooleanField(default=True, help_text="Rejalashtirilgan xabar yuborildi yoki yo'qligi. Darhol yuborilganlar True."),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Xabar kelajakda ma'lum vaqtda yuboriladi. Bo'sh bo'lsa — darhol yuboriladi.", null=True),
        ),
    ]
