# Generated by Django 6.0.5 on 2026-09-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0006_aiusagelog_broadcast_is_sent_broadcast_scheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Modulning unikal identifikatori, masalan: flashcards', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Modul nomi (o'zbek tilida)", max_length=150)),
                ('description', models.TextField(blank=True, help_text="Modul vazifasi haqida qisqacha ma'lumot")),
                ('category', models.CharField(choices=[('core', 'Asosiy'), ('learning', "Ta'lim & O'rganish"), ('gamification', 'Geymifikatsiya & Jang'), ('analytics', 'Analitika')], default='learning', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text="Barcha o'quvchilar uchun yoqilganmi?")),
                ('admin_only', models.BooleanField(default=False, help_text="Faqat Super Adminlar ko'rishi uchunmi? (Beta test)")),
                ('badge_text', models.CharField(blank=True, help_text="Masalan: '2.0 Beta', 'Tez kunda'", max_length=50)),
                ('target_route', models.CharField(blank=True, help_text="Frontend yo'li, masalan: /flashcards", max_length=150)),
                ('icon_name', models.CharField(blank=True, default='Sparkles', help_text='Lucide ikonka nomi', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Funksiya bayrog'i (Feature Flag)",
                'verbose_name_plural': 'Funksiya bayroqlari (Feature Flags)',
                'ordering': ['category', 'key'],
            },
        ),
    ]
