# Generated by Django 6.0.5 on 2026-07-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(default=30)),
                ('features_list', models.TextField(help_text='Newline-separated features list')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Muvaffaqiyatli'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('provider_tx_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.subscriptionplan')),
            ],
        ),
    ]
