# Generated by Django 6.0.5 on 2026-07-08 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='provider_tx_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('web', 'Web App'), ('bot', 'Telegram Bot')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('lessons', 'Video/Audio darslar (oylik obuna)'), ('mock_test', 'Mock test tizimi (bir martalik)')], default='lessons', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('awaiting_screenshot', 'Skrinshot kutilmoqda'), ('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='awaiting_screenshot', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='0 = muddatsiz (bir martalik xarid uchun)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features_list',
            field=models.TextField(blank=True, help_text='Har bir qatorda bitta xususiyat'),
        ),
    ]
