# Generated by Django 5.0 on 2026-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_alter_payment_options_alter_subscriptionplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('awaiting_screenshot', 'Skrinshot kutilmoqda'), ('pending', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], db_index=True, default='awaiting_screenshot', max_length=20),
        ),
    ]
