# Generated by Django 6.0.5 on 2026-08-21 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0005_normalize_plan_order'),
        ('tests_app', '0019_attemptanswer_answered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='test',
            field=models.ForeignKey(blank=True, help_text='Faqat mock test tarifi uchun: qaysi test sotib olindi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tests_app.testset'),
        ),
    ]
