# Generated by Django 6.1 on 2026-09-05 16:42

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_clear_placeholder_telegram_username'),
        ('teacher', '0002_teacherprofile_payout_card_last4_and_more'),
        ('tests_app', '0024_alter_question_tfng_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tiyin', models.PositiveIntegerField(help_text="To'langan summa, TIYINDA.")),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme')], max_length=10)),
                ('provider_transaction_id', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text="Provayderdan kelgan so'rovning o'zgartirilmagan tanasi.")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'lov (provayder)",
                'verbose_name_plural': "To'lovlar (provayder)",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scheduled_start', models.DateTimeField(db_index=True, help_text="Boshlanish vaqti — UTC da saqlanadi, panelda Toshkent vaqtida ko'rsatiladi.")),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('scheduled', "Jadvalga qo'yilgan"), ('live', 'Ketmoqda'), ('finished', 'Tugagan')], db_index=True, default='draft', max_length=10)),
                ('is_free_preview', models.BooleanField(default=False, help_text="Birinchi mock reklama uchun: obunasiz o'quvchi ham kira oladi.")),
                ('results_published_at', models.DateTimeField(blank=True, help_text='Reyting hisoblangan va natijalar yuborilgan vaqt. Ikki marta yuborilmasligi uchun.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='tests_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_tests', to='teacher.teacherprofile')),
                ('test_set', models.ForeignKey(help_text="Savollar manbai. Mavjud test to'plami qayta ishlatiladi.", on_delete=django.db.models.deletion.PROTECT, related_name='mock_tests', to='tests_app.testset')),
            ],
            options={
                'verbose_name': 'Mock test',
                'verbose_name_plural': 'Mock testlar',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, help_text='Foiz. Pul emas, shuning uchun float mumkin.', null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text="Bo'limlar kesimidagi natija.")),
                ('rank', models.PositiveIntegerField(blank=True, help_text="Shu mock ichidagi o'rin. Mock tugagach bir marta hisoblanadi.", null=True)),
                ('result_sent_at', models.DateTimeField(blank=True, help_text='Telegram xabari yuborilgan vaqt (takror yuborilmasligi uchun).', null=True)),
                ('attempt', models.OneToOneField(blank=True, help_text='Javoblar va baholash shu urinishda — mavjud test dvigateli qayta ishlatiladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_attempt', to='tests_app.attempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_attempts', to='accounts.profile')),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='classroom.mocktest')),
            ],
            options={
                'verbose_name': 'Mock urinishi',
                'verbose_name_plural': 'Mock urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_tiyin', models.PositiveIntegerField(help_text="To'lovning to'liq summasi, tiyinda.")),
                ('platform_fee_tiyin', models.PositiveIntegerField(help_text='Platforma ushlab qolgan qismi, tiyinda.')),
                ('net_tiyin', models.PositiveIntegerField(help_text="O'qituvchiga tegishli qism, tiyinda.")),
                ('status', models.CharField(choices=[('accrued', 'Hisoblandi'), ('paid', "To'landi")], db_index=True, default='accrued', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text="Qo'lda to'lash izohi (o'tkazma raqami va h.k.).", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_entry', to='classroom.payment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_entries', to='teacher.teacherprofile')),
            ],
            options={
                'verbose_name': 'Daromad qatori',
                'verbose_name_plural': 'Daromad defteri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_tiyin', models.PositiveIntegerField(help_text="Oylik narx, TIYINDA (40 000 so'm = 4 000 000).")),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='active', max_length=10)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subscriptions', to='accounts.profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='teacher.teacherprofile')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='classroom.subscription'),
        ),
        migrations.CreateModel(
            name='AIGradingQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="YYYY-MM (UTC bo'yicha).", max_length=7)),
                ('used', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grading_quotas', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'AI baholash chegarasi',
                'verbose_name_plural': 'AI baholash chegaralari',
                'ordering': ['-period'],
                'unique_together': {('student', 'period')},
            },
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['teacher', 'scheduled_start'], name='mock_teacher_start_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['status', 'scheduled_start'], name='mock_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='mockattempt',
            index=models.Index(fields=['mock', '-score'], name='mockattempt_mock_score_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mockattempt',
            unique_together={('student', 'mock')},
        ),
        migrations.AddIndex(
            model_name='payoutentry',
            index=models.Index(fields=['teacher', 'status'], name='payout_teacher_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutentry',
            constraint=models.CheckConstraint(condition=models.Q(('gross_tiyin', django.db.models.expressions.CombinedExpression(models.F('platform_fee_tiyin'), '+', models.F('net_tiyin')))), name='payout_split_adds_up'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['student', 'status'], name='sub_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['teacher', 'status'], name='sub_teacher_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'teacher'), name='uniq_active_subscription_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_transaction_id'), name='uniq_provider_transaction'),
        ),
    ]
