# Generated by Django 6.1 on 2026-09-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': "Obuna to'lovi", 'verbose_name_plural': "Obuna to'lovlari"},
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='uniq_provider_transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Rad etish sababi yoki izoh.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, help_text="O'tkazma cheki skrinshoti.", null=True, upload_to='classroom/receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_class_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('card', "Karta o'tkazmasi"), ('click', 'Click'), ('payme', 'Payme')], default='card', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, help_text="O'tkazma / tranzaksiya raqami. Karta o'tkazmasida ixtiyoriy, lekin yozilsa — bir xil chek ikkinchi marta kiritilmaydi.", max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text="So'rovning o'zgartirilmagan tanasi (provayder yoki o'quvchi kiritgani)."),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('success', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='uniq_provider_transaction'),
        ),
    ]
