# Generated by Django 6.0.5 on 2026-07-10 17:14

from django.db import migrations, models


def mark_existing_profiles_as_onboarded(apps, schema_editor):
    """Existing users already know the app; only new signups going forward
    should see the onboarding splash screens."""
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.update(has_seen_onboarding=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_premium_mock_test_unlocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False, help_text="Loyiha haqida tanishtiruv splash-ekranlarini ko'rganmi"),
        ),
        migrations.RunPython(mark_existing_profiles_as_onboarded, noop),
    ]
