# Generated by Django 6.0.5 on 2026-07-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_has_seen_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('teacher', "O'qituvchi"), ('student', "O'quvchi")], db_index=True, default='student', help_text="Foydalanuvchi roli. Boshqaruv panellariga kirish shu bo'yicha aniqlanadi.", max_length=20),
        ),
    ]
