# Generated by Django 6.0.5 on 2026-07-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text="Kim taklif qilgan (birinchi ro'yxatdan o'tishdagina o'rnatiladi).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='ReferralBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_awarded', models.PositiveIntegerField(default=10, help_text='Coins the REFERRER received (the new user gets the same amount).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonus_received', to='accounts.profile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_bonuses_given', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', '-created_at'], name='accounts_re_referre_c9868a_idx')],
            },
        ),
    ]
