# Generated by Django 6.0.5 on 2026-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolesson',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Faqat premium (oylik obuna) foydalanuvchilarga ochiq'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Faqat premium (oylik obuna) foydalanuvchilarga ochiq'),
        ),
    ]
