# Generated by Django 6.0.5 on 2026-07-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_backfill_lesson_publish_owner'),
        ('tests_app', '0014_alter_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='tests_app.subject'),
        ),
    ]
