# Generated by Django 6.1 on 2026-09-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_topic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('history', 'Tarix'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
    ]
