# Generated by Django 6.1 on 2026-09-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_topic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('history', 'Mavzulashtirilgan'), ('certificate', 'Milliy Sertifikat'), ('bba', 'BBA Imtihoni'), ('cefr', 'CEFR')], default='history', max_length=20),
        ),
    ]
