# Generated by Django 6.1 on 2026-09-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_topic_category'),
        ('tests_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Masalan: Tarix, Ona tili, Biologiya', max_length=100)),
                ('subject_slug', models.CharField(db_index=True, help_text='Masalan: tarix, ona-tili, biologiya', max_length=100)),
                ('category_badge', models.CharField(help_text='Masalan: Amir Temur & Anqara jangi (1402)', max_length=150)),
                ('tagline', models.CharField(default='Bilasizmi?', help_text="Masalan: Bilasizmi?, Eng ko'p xato qilingan!, Oltin Qoida", max_length=100)),
                ('hook', models.CharField(help_text='Diqqatni tortuvchi savol yoki fakt sarlavhasi', max_length=300)),
                ('fact', models.TextField(help_text='2-3 ta qisqa va qiziqarli tushuntirish jumlasi')),
                ('takeaway', models.CharField(help_text='Oltin xulosa / imtihon qoidasi', max_length=300)),
                ('quiz_question', models.TextField(help_text='Variantli savol matni')),
                ('quiz_options', models.JSONField(default=list, help_text="4 ta variantlar ro'yxati")),
                ('quiz_correct_index', models.IntegerField(default=0, help_text="To'g'ri variant indeksi (0, 1, 2 yoki 3)")),
                ('quiz_explanation', models.TextField(blank=True, help_text="Javob berilgach ko'rsatiladigan qisqa tushuntirish")),
                ('gradient_theme', models.CharField(choices=[('rose', 'Qizil Otash (Rose/Pink)'), ('sky', 'Moviy Osmon (Sky/Cyan)'), ('emerald', 'Yashil Zumrad (Emerald/Teal)'), ('purple', 'Binafsharang Neon (Purple/Indigo)'), ('amber', 'Oltin Quyosh (Amber/Orange)')], default='purple', max_length=30)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text="O'quvchilar lentasiga chiqarish")),
                ('order', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reels', to=settings.AUTH_USER_MODEL)),
                ('source_question', models.ForeignKey(blank=True, help_text="Platformadagi qiyin test savoli bilan bog'lanish", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_reels', to='tests_app.question')),
            ],
            options={
                'verbose_name': 'Bilim Reel',
                'verbose_name_plural': 'Bilim Reels',
                'ordering': ['-order', '-id'],
            },
        ),
    ]
