# Generated by Django 6.1 on 2026-09-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_reels_video_and_community_upgrades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reelcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Reel Izohi', 'verbose_name_plural': 'Reel Izohlari'},
        ),
    ]
