# Generated by Django 6.0.5 on 2026-07-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_add_image_to_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Ilm Ildizi', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_channel',
            field=models.CharField(blank=True, help_text='masalan: @ilmildizi', max_length=150),
        ),
    ]
