# Generated by Django 6.0.5 on 2026-07-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_alter_choice_options_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_random',
            field=models.BooleanField(default=False, help_text='One-off test generated for a single random-quiz attempt; hidden from the browsable catalog.'),
        ),
    ]
