# Generated by Django 6.0.5 on 2026-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_test_is_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='Mock test tizimi uchun bir martalik xarid qilganlargagina ochiq. Tasodifiy test har doim bepul.'),
        ),
    ]
