# Generated by Django 6.0.5 on 2026-07-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0007_groupoption_attemptanswer_matching_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Test katalogida ko'rinmaydi, lekin o'chirilmaydi — foydalanuvchilarning bu testga oid eski urinishlari (Attempt) va ballari to'liq saqlanib qoladi."),
        ),
    ]
