# Generated by Django 6.0.5 on 2026-07-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0010_alter_question_reference_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Testni yaratgan o'qituvchi/admin. Teacher panelda faqat o'z testlari ko'rinadi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testset',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Qoralama (draft) yoki nashr etilgan. Faqat nashr etilgan testlar o'quvchilar katalogida ko'rinadi. Tasodifiy testlar bundan mustasno."),
        ),
        migrations.AddField(
            model_name='testset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
