# Generated by Django 6.0.5 on 2026-07-16 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_superadmin_role'),
        ('tests_app', '0014_alter_question_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, help_text="Savol tegishli fan. Test to'plamiga qo'shilganda avtomatik to'ldiriladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests_app.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#2d6cff', help_text='Fan uchun asosiy rang (hex).', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon_name',
            field=models.CharField(default='book', help_text='Lucide ikonka nomi (masalan: book, calculator, flask-conical).', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_scores', to='accounts.profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tests_app.subject')),
            ],
            options={
                'ordering': ['-xp'],
                'unique_together': {('profile', 'subject')},
            },
        ),
    ]
