# Generated by Django 6.0.5 on 2026-07-06 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        # Must be the migration that renames Choice -> AnswerOption (0009) or later —
        # not 0001. The FK below uses the post-rename name; depending on 0001 only
        # requires tests_app to have run *at least* that far, which lets Django's
        # migration-graph topological sort legally place this migration's CreateModel
        # either before OR after the 0009 rename. If it lands after (which it now does,
        # since a later battles migration's dependency on a much-later tests_app
        # migration nudges the sort), 'tests_app.choice' no longer resolves in the
        # replayed historical state — surfaced by `manage.py test`'s from-scratch
        # migration run, not by `makemigrations --check` against an already-migrated
        # dev database.
        ('tests_app', '0009_universal_test_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('searching', 'Mos raqib qidirilmoqda'), ('active', 'Jang davom etmoqda'), ('finished', 'Tugallangan')], default='searching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_p1', to='accounts.profile')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_p2', to='accounts.profile')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='battles.battle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.question')),
            ],
            options={
                'unique_together': {('battle', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='BattlePlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time_ms', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests_app.answeroption')),
                ('battle_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='battles.battleround')),
            ],
            options={
                'unique_together': {('battle_round', 'player')},
            },
        ),
    ]
