# Generated by Django 6.0.5 on 2026-07-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_battle_bot_avatar_url_battle_bot_elo_rating_and_more'),
        ('tests_app', '0017_revisionitem_subjectscore_subjscore_subj_xp_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_app.subject'),
        ),
    ]
