# Generated by Django 5.0 on 2026-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_battle_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('searching', 'Mos raqib qidirilmoqda'), ('active', 'Jang davom etmoqda'), ('finished', 'Tugallangan')], db_index=True, default='searching', max_length=20),
        ),
    ]
