# Generated by Django 6.1 on 2026-09-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0004_alter_battle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('pending', 'Chaqiruvga javob kutilmoqda'), ('searching', 'Mos raqib qidirilmoqda'), ('active', 'Jang davom etmoqda'), ('finished', 'Tugallangan')], db_index=True, default='searching', max_length=20),
        ),
    ]
