"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to a dev-only key so `manage.py` still runs if .env is missing —
# always set a real SECRET_KEY via .env outside of local development.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-only-fallback-key-do-not-use-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    '127.0.0.1', 'localhost',
    '.pythonanywhere.com',                                  # production host
    '.loca.lt', '.ngrok-free.dev', '.ngrok-free.app', '.ngrok.io',  # dev tunnels
]

# Needed because tunnels and PythonAnywhere serve over HTTPS while proxying to plain HTTP —
# Django's CSRF middleware checks the browser's Origin header against this list for any
# secure (HTTPS) request, and rejects it (403) if the domain isn't trusted.
CSRF_TRUSTED_ORIGINS = [
    'https://*.pythonanywhere.com',
    'https://*.loca.lt',
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
]

# Moving to a custom domain later needs no code change — set EXTRA_ALLOWED_HOSTS in the
# environment (comma-separated, e.g. "ilmmevasi.uz,www.ilmmevasi.uz") and both lists pick
# it up. Bare hosts are also trusted as HTTPS origins for CSRF.
_extra_hosts = [h.strip() for h in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS += _extra_hosts
CSRF_TRUSTED_ORIGINS += [h if h.startswith('http') else f'https://{h.lstrip(".")}' for h in _extra_hosts]
    
# Telegram bot token used to validate Telegram WebApp login data. Set in .env.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# Public HTTPS base URL of this site — used for the Mini App button and to build the
# webhook URL. Telegram rejects non-HTTPS for both.
WEBAPP_URL = os.environ.get('WEBAPP_URL', 'http://127.0.0.1:8000/')

# Shared secret Telegram echoes back in X-Telegram-Bot-Api-Secret-Token on every webhook
# call. Without it anyone who guesses the URL could POST fake updates, so the endpoint
# refuses to run when this is unset. Generate with: python -c "import secrets;print(secrets.token_urlsafe(32))"
TELEGRAM_WEBHOOK_SECRET = os.environ.get('TELEGRAM_WEBHOOK_SECRET', '')
TELEGRAM_WEBHOOK_MAX_CONNECTIONS = int(os.environ.get('TELEGRAM_WEBHOOK_MAX_CONNECTIONS', '40'))

# Chat that receives new-payment notifications (optional; must be a numeric chat id).
ADMIN_TELEGRAM_CHAT_ID = os.environ.get('ADMIN_TELEGRAM_CHAT_ID', '')

# Google OAuth client id for "Sign in with Google" on the website (NOT the Telegram Mini
# App). Create an OAuth 2.0 Web client at https://console.cloud.google.com/apis/credentials
# and add your site origin(s) to "Authorized JavaScript origins". When empty, the Google
# button simply isn't rendered, so the site keeps working with classic + Telegram login.
#
# The fallback below is the project's real client id. A Google OAuth *client id* is public
# by design (it ships in the page's HTML for the browser to use), so committing it is safe
# and means `git pull` alone enables the button on any server — no .env edit needed. Set
# GOOGLE_OAUTH_CLIENT_ID in the environment to override it (e.g. a separate staging client).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get(
    'GOOGLE_OAUTH_CLIENT_ID',
    '534089827568-olhigpeig64rioppsgttm1u1sltuln4i.apps.googleusercontent.com',
)

# Card shown to students for premium payments. Set in .env.
PREMIUM_CARD_NUMBER = os.environ.get('PREMIUM_CARD_NUMBER', '0000 0000 0000 0000')
PREMIUM_CARD_HOLDER = os.environ.get('PREMIUM_CARD_HOLDER', "Ism Familiya (kartani .env faylida kiriting)")

# Groq Cloud API key (https://console.groq.com) used for the AI Mentor chat and the
# post-test AI feedback. Set in .env; when empty, both features fall back to their
# built-in rule-based logic instead of failing.
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.3-70b-versatile')

# Lokal Ollama zaxira (ixtiyoriy): Groq kaliti yo'q yoki limitga urilganda AI
# funksiyalari (mentor chat, test feedback, xato izohlari) shu lokal server
# orqali ishlashda davom etadi. Bo'sh qoldirilsa — zaxira o'chirilgan bo'ladi.
# Masalan: OLLAMA_API_URL=http://localhost:11434
OLLAMA_API_URL = os.environ.get('OLLAMA_API_URL', '')
OLLAMA_AI_MODEL = os.environ.get('OLLAMA_AI_MODEL', 'qwen3:8b')


# Application definition

INSTALLED_APPS = [
    'adminsortable2',
    'django_ckeditor_5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'dashboard.apps.DashboardConfig',
    'accounts.apps.AccountsConfig',
    'analytics.apps.AnalyticsConfig',
    'battles.apps.BattlesConfig',
    'games.apps.GamesConfig',
    'leaderboard.apps.LeaderboardConfig',
    'learning.apps.LearningConfig',
    'panel.apps.PanelConfig',
    'premium.apps.PremiumConfig',
    'shop.apps.ShopConfig',
    'teacher.apps.TeacherConfig',
    'telegrambot.apps.TelegramBotConfig',
    'tests_app.apps.Tests_appConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves compressed, far-future-cached static files straight from Django in
    # production (no separate nginx needed). Must sit right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'panel.middleware.CurrentUserMiddleware',
    'panel.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'panel.context_processors.site_settings',
                'shop.context_processors.shop_equipped',
            ],
        },
    },
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite serialises every write behind a single lock — it cannot survive real concurrency.
# Set DATABASE_URL (e.g. postgres://user:pass@host:5432/dbname) and the app runs on
# PostgreSQL with no code change. CONN_MAX_AGE keeps connections alive between requests
# instead of paying a new TCP+auth handshake on every single one; health checks drop
# connections that a proxy/DB restart has already killed.
DATABASE_URL = os.environ.get('DATABASE_URL', '')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get('CONN_MAX_AGE', '60')),
            conn_health_checks=True,
            ssl_require=os.environ.get('DB_SSL_REQUIRE', 'False') == 'True',
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # Wait instead of instantly erroring with "database is locked" under load.
            'OPTIONS': {'timeout': 20},
        }
    }


# Cache
# One knob scales the whole app: set REDIS_URL in .env (e.g. redis://127.0.0.1:6379/1)
# and every cache.get_or_set / per-profile cache transparently moves to Redis — no code
# change. Without it, the in-process LocMem cache is used, so development and the current
# ~small deployment run with zero extra services. Django 6 ships the Redis backend
# natively (only the `redis` pip package is needed when REDIS_URL is set).
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ilmmevasi-local',
        }
    }

# Sessions: by default Django reads the session row from the DB on EVERY request, which
# at scale is the single most repeated query in the app. With Redis configured we serve
# reads from cache and still persist to the DB, so nothing is lost if Redis is flushed.
# Without Redis the cache is per-process, so the plain DB backend stays correct.
if REDIS_URL:
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Destination for `collectstatic` — the single folder WhiteNoise serves in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# In production, hash + compress static files (long-term caching, gzip/brotli). Kept off
# in DEBUG so the dev server serves straight from source with no collectstatic step.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG else
            'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Media files (payment screenshots, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Production hardening. These only switch on when DEBUG is off, so local development
# over plain HTTP is unaffected, but a real deployment gets secure cookies, HTTPS
# redirects, and clickjacking/content-type protections without any extra config.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Behind a TLS-terminating proxy (ngrok, nginx, most PaaS), trust its forwarded scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Rich-text editor for Question.body (CKEditor 5 — the maintained, non-vulnerable
# successor to CKEditor 4). Includes a table tool so admins can build the HTML tables
# that table_based questions (e.g. "Asr / Voqea" grids) need.
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', '|',
            'bulletedList', 'numberedList', '|', 'insertTable', 'blockQuote', '|',
            'undo', 'redo',
        ],
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
    },
}
CKEDITOR_5_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
