# Generated by Django 6.0.5 on 2026-07-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_backfill_superadmin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('avatar', 'Avatar'), ('frame', 'Ramka'), ('theme', 'Mavzu'), ('title', 'Unvon'), ('badge', 'Nishon'), ('consumable', 'Sarflanadigan')], db_index=True, max_length=20)),
                ('slug', models.SlugField(help_text="Barqaror mashina-nomi — seed va kod shu bo'yicha topadi.", unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('icon_name', models.CharField(default='sparkles', help_text='Lucide ikonka nomi.', max_length=50)),
                ('price_coins', models.PositiveIntegerField(default=100)),
                ('rarity', models.CharField(choices=[('common', 'Oddiy'), ('rare', 'Noyob'), ('epic', 'Epik'), ('legendary', 'Afsonaviy')], default='common', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Turga xos render ma'lumoti: avatar uchun {'avatar_url': ...}, ramka uchun {'class': 'frame-gold'}, unvon uchun {'title': '...'} va hokazo.")),
                ('is_consumable', models.BooleanField(default=False, help_text="True bo'lsa bir necha marta olinadi va miqdor sifatida to'planadi (masalan Streak Freeze).")),
                ('required_level', models.PositiveIntegerField(default=0, help_text='Shu darajadan past foydalanuvchilar sotib ololmaydi (0 = cheklovsiz).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'price_coins', 'id'],
                'indexes': [models.Index(fields=['category', 'is_active', 'order'], name='shop_shopit_categor_18da3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text="Snapshot — mahsulot o'chsa ham tarix o'qiladi.", max_length=120)),
                ('coins_spent', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.profile')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='shop.shopitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', '-created_at'], name='shop_purcha_profile_a78bd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='accounts.profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='shop.shopitem')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'is_equipped'], name='shop_invent_profile_b40794_idx')],
                'unique_together': {('profile', 'item')},
            },
        ),
    ]
