# Generated by Django 6.0.5 on 2026-08-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_profile_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('subject', models.CharField(blank=True, help_text='Masalan: Tarix, Ona tili', max_length=80)),
                ('institution', models.CharField(blank=True, help_text="Maktab / o'quv markazi nomi", max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='accounts.profile')),
            ],
            options={
                'verbose_name': "O'qituvchi profili",
                'verbose_name_plural': "O'qituvchi profillari",
            },
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_link', to='accounts.profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='accounts.profile')),
            ],
            options={
                'verbose_name': "Sinf o'quvchisi",
                'verbose_name_plural': "Sinf o'quvchilari",
                'ordering': ['-joined_at'],
            },
        ),
    ]
