# Generated by Django 6.1 on 2026-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='payout_card_last4',
            field=models.CharField(blank=True, help_text="Karta raqamining FAQAT oxirgi 4 raqami — to'lovni kim olganini tekshirish uchun. To'liq raqam saqlanmaydi.", max_length=4),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='revenue_share_percent',
            field=models.PositiveSmallIntegerField(default=75, help_text="O'qituvchiga tegadigan ulush, foizda. Qolgani platformada qoladi."),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='telegram_channel_url',
            field=models.URLField(blank=True, help_text="O'qituvchining Telegram kanali (o'quvchilarga ko'rsatiladi).", max_length=300),
        ),
    ]
