# Generated by Django 5.0 on 2026-08-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0017_revisionitem_subjectscore_subjscore_subj_xp_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateField(db_index=True, unique=True)),
                ('channel_message_id', models.PositiveBigIntegerField(blank=True, help_text='Telegram message_id of the post in the channel (for reference/deep-link building).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_channel_posts', to='tests_app.question')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
