# Generated by Django on 2026-09-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Kanal nomi (masalan: 'Ilm Ildizi Rasmiy')", max_length=150)),
                ('username_or_id', models.CharField(help_text='@username yoki raqamli -100... id', max_length=150)),
                ('invite_url', models.URLField(blank=True, help_text='Kanal havolasi (masalan: https://t.me/ilmildizi)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text="Faol holatda o'quvchilardan a'zolik talab qilinadi")),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
