# Generated by Django 6.0.5 on 2026-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('clue_1', models.CharField(help_text='Easiest/broadest clue', max_length=500)),
                ('clue_2', models.CharField(help_text='Medium difficulty clue', max_length=500)),
                ('clue_3', models.CharField(help_text='Hardest/most specific clue', max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(help_text='Historical year (negative for BC)')),
                ('description', models.TextField(blank=True)),
                ('era', models.CharField(choices=[('ancient', 'Qadimgi Davr'), ('medieval', "O'rta Asrlar"), ('modern', 'Yangi va Eng Yangi Davr')], default='medieval', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MapChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('geojson_data', models.TextField(blank=True, help_text='GeoJSON representing empire boundaries/locations')),
                ('correct_location', models.CharField(help_text='Name of city/region or coords', max_length=150)),
                ('map_image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
