# Generated by Django 6.0.5 on 2026-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchallenge',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of selectable region names shown to the player; one must match correct_location'),
        ),
    ]
