# Generated by Django 6.0.5 on 2026-07-17 19:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profile_xp_desc_idx'),
        ('core', '0002_alter_profilemission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('sent_ok', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_reminders', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
